### ISSUE TITLE
Importing TCT .des files

### ISSUE THREAD

**Issue by raywu2478** [krudie/IDES#1] opened 2020-12-10 00:10 UTC
I am trying to import a TCT file into IDES and I am running into an error saying it is not a TCT file.
![image](https://user-images.githubusercontent.com/8943426/101703925-9ca8c400-3a51-11eb-96ac-66a1a5d168fa.png)

I found that if I try to import a TCT file that was originally exported from IDES everything is fine. But if the file was created in TCT the error shows up. 

I have attached an example file that was created in TCT
[M1.zip](https://github.com/krudie/IDES/files/5669433/M1.zip)

**Comment by Ritsuka314** [comment] 2020-12-10 07:35
Hello Ray,

I'm not a maintainer of the IDES tool but here is my $.02.

The issue is the version of the TCT tool you are using.

If you open the example file you provided as a text file,
you will find at the begining the string `TCT DES file. Version 1.0 Z8^0L;2`,
with one undisplayable character between `1.0` and `Z8`.
The `Z8^0L;2` part presumablly indicates the version of the TCT file format.

IDES 3.1.2 is currently only capable to process TCT file in the format versioned `1.0 Z8^0L;1`.
For the particular example file you provided,
simply changing `Z8^0L;2` to `Z8^0L;1` does not seem to cause any compatibility problem:
IDES imported it as an automaton with three states 0, 1, 2, with state 0 being initial and marked, and no transition between states.
If this is how you generated the example file,
then there might be a chance that this approach is going to work for your other files too.

While I am not an official maintainer of IDES,
I'd still be happy to take a further look into the issue.
I will have to take a look of what changed between `Z8^0L;1` and `Z8^0L;2` so I can update IDES accordingly.
One thing I need your help is,
since I couldn't access the [webpage of TCT](http://www.control.utoronto.ca/cgi-bin/dlxptct.cgi),
which I found [here](https://www.control.utoronto.ca/DES/Research.html),
can you point me to the webpage of TCT, or perhaps where its source code is hosted?

**Comment by raywu2478** [comment] 2020-12-10 15:13
Hey thanks for your response.

The result of your import doesn't sound right. There should be transitions between the states. I attached the output of CE command from TCT. 
![M1](https://user-images.githubusercontent.com/8943426/101788445-18e0ed00-3ace-11eb-9cbe-0e6ae5ea7159.GIF)

I also tried editing the .des file but if I try to import the edited file I get this error
![image](https://user-images.githubusercontent.com/8943426/101789077-d5d34980-3ace-11eb-9351-aa0d7f88cdf9.png)

The link you used is where I downloaded TCT previously. I don't know where else they are hosted. I'll attach the two versions of TCT I have
[TCTX64_Public_20200826.zip](https://github.com/krudie/IDES/files/5673669/TCTX64_Public_20200826.zip)
[TCT_20170501.zip](https://github.com/krudie/IDES/files/5673685/TCT_20170501.zip)

**Comment by Ritsuka314** [comment] 2020-12-11 09:42
The error `Unsupported TCT number encoding` is caused because when changing `Z8^0L;2` to `Z8^0L;1` you accidentally modified the four bytes proceeding.
But that doesn't matter anyway.
The example indicates significant changes made to the format of .des files,
so manually editing your .des files is not going to help.

Since TCT was recently updated in August,
the website must be down temporarily.
As soon as it is back I will look into it.
Maybe I can write a patch for IDES.

**Comment by lenkog** [comment] 2020-12-18 02:24
@raywu2478 - thank you for reporting this issue. I guess at the moment I'm the closest to an "official maintainer" of IDES :-).
I believe that @RichardYan314's analysis is correct and the file format of the latest CTCT software is different than the format supported by IDES.
I have reached out to Dr. Wonham's team for confirmation. Hopefully, we'll hear back and we'll get more information about the new format. This would make it easier to implement support for it in IDES.

**Comment by lenkog** [comment] 2020-12-22 00:24
Good news - we received details about the changes in the 64-bit version of TCT. I implemented preliminary support for the new file format.
@raywu2478 - Could you grab the latest IDES release (https://github.com/krudie/IDES/releases/tag/v3.1.3-201221181349) and try it out? Please let us know how it goes. Thanks.

**Comment by raywu2478** [comment] 2020-12-22 00:35
Hey @lenkog thank you so much for getting an update out so quickly. The import from TCT feature appear to be working great with every file  I tested.

**Comment by lenkog** [comment] 2020-12-22 04:27
Great! Will be part of v3.1.3.

**Closed as completed by lenkog** 2020-12-22 04:27 UTC
