### ISSUE TITLE
First state label lower when exported as .eps

### ISSUE THREAD

**Issue by BrynneXVII** [krudie/IDES#2] opened 2023-02-06 19:41 UTC
When diagrams are exported as .eps files, the first state label is dropped lower than all of the other labels. This seems to only be an issue for .eps files not pngs. It is extremely apparent with a larger font size.

Unsure whether this issue is present when not using latex rendering.

![ides_issue](https://user-images.githubusercontent.com/37638706/217068555-b2b51d74-359f-4fb1-ac79-ea12447ab9c5.png)

**Comment by Ritsuka314** [comment] 2023-02-06 19:46
Can you save your model as `.xmd` file and upload it with your `.eps` file?

**Comment by lenkog** [comment] 2023-02-08 03:22
@BrynneXVII - This is a known issue (see readme - "Node labels may not be centered properly when exporting to LaTeX or EPS"). The misalignment seems to affect the node label "1" in particular, but has been observed also with other labels.
Unfortunately, we haven't been able to track down the reason for this. If you are inclined to investigate, we'd be glad to get help.

**Comment by Ritsuka314** [comment] 2023-02-14 19:37
Somehow the state label became `\hspace{1mm}1\hspace{1mm}` in @BrynneXVII's `.xmd` model. All it took me to fix the problem is to edit the node and replace the label. I really couldn't figure out how the `\hspace` got in there; but it doesn't look like a problem of IDES.

The LaTeX/eps output seems to be all right after that.

**Comment by lenkog** [comment] 2023-03-09 03:29
@Ritsuka314 or @BrynneXVII - could you share the .xmd file?

**Comment by lenkog** [comment] 2023-04-22 19:09
@BrynneXVII - FYI, this issue is fixed in v3.1.4

**Closed as completed by lenkog** 2023-04-22 19:09 UTC
